# BASE UI
ColorColumn: 'watermelon .'
Conceal: ''
Cursor: ''
CursorIM: ''
CursorColumn: ''
CursorLine: '. lineHighlightBackground'
Directory: ''
DiffAdd: 'background lime'
DiffChange: 'background orange'
DiffDelete: 'background watermelon'
DiffText: 'background lime'
ErrorMsg: ''
VertSplit: 'background . .'
Folded: 'gray5 background'
FoldColumn: 'gray3 background'
SignColumn: '- background'
LineNr: 'lineNumber background'
CursorLineNr: 'lineNumberHighlight'
Normal: 'foreground background'
MatchParen: ''
ModeMsg: ''
MoreMsg: ''

NonText: 'gray4 .'
PMenu: '. eggplant'
PMenuSel: '. plum'

PmenuSbar: ''
PmenuThumb: ''
Question: ''
IncSearch: 'highlight orange'
# Search -> when pressing *
Search: 'background orange'
SpecialKey: 'orange .'
SpellBad: ''
SpellLocal: ''
SpellCap: ''
SpellRare: ''
StatusLine: ''
StatusLineNC: ''
TabLine: ''
TabLineFill: ''
TabLineSel: ''
Title: 'blueberry . b'
Visual: 'foreground eggplant'
VisualNOS: ''
WarningMsg: ''
WildMenu: ''

# BASE SYNTAX
Comment: 'gray . i'
Constant: 'lime .'
String: 'orange .' # Constant
Character: '' # Constant
Boolean: '#ff5874 .' # Constant
Number: 'tangerine .' # Constant
Float: '' # Constant
Identifier: 'mint .'

Function: 'plum .' # Identifier
Statement: 'plum . i'
Conditional: '' # Statement
Repeat: '' # Statement
Label: '' # Statement
Operator: 'plum .' # Statement
Keyword: 'lime .' # Statement
Exception: '' # Statement
PreProc: 'plum .'
Include: '' # PreProc
Define: '' # PreProc
Macro: '' # PreProc
PreCondit: '' # PreProc
Type: 'lime . i'
# let or const
StorageClass: 'plum .' # Type
Structure: '' # Type
Typedef: '' # Type
Special: ''
SpecialChar: '' # Special
Tag: 'gray' # Special
Delimiter: '' # Special
SpecialComment: '' # Special
Debug: '' # Special
Underlined: ''
Ignore: ''
Error: ''
Todo: ''

# html
htmlTag: 'mint .'
htmlEndTag: '@htmlTag'
htmlTagName: 'watermelon . i'

# Javascript - pangloss/vim-javascript
CLArrowFunction: 'plum .'
CLVariableDeclaration: 'blueberry . i'
CLGrammarSymbols: 'plum .'
CLExport: 'plum . i'

# Javascript
jsConditional: '@Statement'
jsClassKeyword: 'plum'
jsClassDefinition: 'orange'
jsExtendsKeyword: 'plum . i'
jsClassFuncName: 'blueberry . i'
jsClassProperty: '@jsClassFuncName'
jsFuncCall: '@jsClassFuncName'
jsFunction: 'plum'
jsExport: 'plum . i'
jsExportDefault: '@jsExport'
jsSuper: 'mint'
jsThis: 'mint'
jsObjectProp: 'mint'
jsObjectKey: 'plum . i'
jsObjectValue: 'mint . i'
jsDot: 'plum'
jsNull: 'watermelon'
jsArrowFunction: '@CLArrowFunction'
jsString: '@String'
jsOperator: 'plum .'
jsImport: 'plum . i'
jsFrom: '@jsImport'
jsReturn: '@Statement'
jsStorageClass: '@StorageClass'
jsDestructuringBlock: 'watermelon'
jsVariableDef: 'blueberry . i'

# JSX
jsxTagName: '@htmlTag'
jsxComponentName: 'tangerine .'
jsxOpenPunct: '@htmlTag'
jsxCloseString: '@htmlTag'
jsxExpressionBlock: 'foreground .'
jsxBraces: 'blueberry .'

# Typescript
typescriptCall: 'foreground .'
typescriptImport: '@jsImport'
typescriptBinaryOp: 'plum .'
typescriptStatementKeyword: '@Statement'
typescriptVariable: '@StorageClass'
typescriptMember: '@CLVariableDeclaration'
typescriptVariableDeclaration: '@CLVariableDeclaration'
typescriptBlock: 'foreground .'
typescriptAliasDeclaration: 'foreground .'
typescriptAliasKeyword: 'plum .'
typescriptAssign: '@Operator'
typescriptTypeReference: 'orange . i'
typescriptUnion: 'mint .'
typescriptArrowFunc: '@CLArrowFunction'
typescriptTypeAnnotation: 'mint .'
typescriptDotNotation: '@CLGrammarSymbols'
typescriptTypeBrackets: '@CLGrammarSymbols'
typescriptProp: 'mint . i'
typescriptObjectLabel: 'foreground .'
typescriptExport: '@CLExport'
typescriptBraces: 'foreground .'
typescriptParens: '@typescriptBraces'

# JSON
jsonBraces: 'foreground .'
jsonKeyword: 'mint .'
jsonString: 'plum .'

# Python
pythonImport: 'plum . i'
pythonFunction: 'blueberry . i'
pythonStatement: 'plum .'
pythonNone: 'watermelon'
pythonBuiltinFunc: 'lime'
pythonDottedName: 'lime'
pythonDecorator: 'lime'
pythonClassVar: 'mint'

# CSS
cssClassName: 'lime . i'
cssClassNameDot: '@cssClassName'
cssIdentifier: 'pineapple . i'
cssTagName: 'watermelon .'
cssBraces: 'foreground .'
cssUnitDecorators: 'banana .'
cssFontProp: 'mint .'
cssPositioningProp: '@cssFontProp'
cssBackgroundProp: '@cssFontProp'
cssDefinition: '@cssFontProp'
cssFontAttr: '@cssUnitDecorators'
cssColor: '@cssFontAttr'


# Yaml

##### nerd tree
NERDTreeDir: 'greyblue .'
NERDTreeOpenable: 'watermelon .'
NERDTreeClosable: 'orange .'
NERDTreeHelp: 'gray4 . i'
NERDTreeUp: 'gray .'
NERDTreeDirSlash: 'gray .'

# Git
GitGutterAdd: 'lime .'
GitGutterChange: 'orange .'
GitGutterDelete: 'watermelon .'
GitGutterChangeDelete: 'orange .'
gitcommitSummary: 'foreground .'

# Markdown and MDX
markdownInlineDelimiter: 'plum . i'
markdownItalic: 'plum . i'
markdownBold: 'lime . b'
markdownItemDelimiter: 'foreground .'
markdownH1: 'blueberry .'
markdownH2: '@markdownH1'
markdownH3: '@markdownH1'
markdownH4: '@markdownH1'
markdownHeadingDelimiter: '@markdownH1'
markdownLinkTextContainer: 'blueberry .'
markdownLinkUrlContainer: 'mint .'
markdownLinkText: 'foreground .'
markdownLinkUrl: 'strawberry .'
markdownRule: 'foreground .'

# Startify
StartifyPath: 'blueberry .'
StartifyFile: 'mint .'
